on:
  push:
    branches:
    - main
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    #environment: oidc
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
          client-id: ba0c6a05-aeb6-45c4-9452-2cd4b0d1da08
          tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
          subscription-id: 909cb1f4-a3f2-4db6-8482-23ceb7e81eb0
      - name: Azure Test
        run: az account show
